config:
    paths:
        'c3': 'bundles/okvpnmqinsight/js/app/c3.min.js'
        'd3': 'bundles/okvpnmqinsight/js/app/d3.min.js'
        'okvpnmqinsight/queued-view': 'bundles/okvpnmqinsight/js/component/queued-view.js'
