parameters:
    okvpn_mq_insight.skip_stat_retrieve: false

services:
    okvpn_mq_insight.provider_dbal:
        class: Okvpn\Bundle\MQInsightBundle\Model\Provider\DbalQueueProvider
        public: false
        arguments: ['@doctrine']
        tags:
            - { name: okvpn.mq_stat_provider, driver: dbal }

    okvpn_mq_insight.queue_provider:
        class: Okvpn\Bundle\MQInsightBundle\Model\Provider\DefaultQueueProvider
        arguments: [~]

    okvpn_mq_insight.debug_message_producer:
        class: Okvpn\Bundle\MQInsightBundle\Client\DebugMessageProducer
        decorates: oro_message_queue.client.message_producer
        arguments:
            - '@okvpn_mq_insight.debug_message_producer.inner'

    okvpn_mq_insight.listener.flush_message:
        class: Okvpn\Bundle\MQInsightBundle\EventListener\MQStatCollectorListener
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@okvpn_mq_insight.debug_message_producer'
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }
            - { name: kernel.event_listener, event: console.terminate, method: onConsoleTerminate }

    okvpn_mq_insight.stat_extension:
        class: Okvpn\Bundle\MQInsightBundle\Extension\MQStatExtension
        arguments: ['@service_container']
        tags:
            - { name: 'oro_message_queue.consumption.extension', persistent: true, priority: 10 }

    okvpn_mq_insight.chart_provider:
        class: Okvpn\Bundle\MQInsightBundle\Provider\QueueChartProvider
        arguments: ['@doctrine']

    okvpn_mq_insight.queued_messages_provider:
        class: Okvpn\Bundle\MQInsightBundle\Provider\QueuedMessagesProvider
        arguments: ['@okvpn_mq_insight.storage']

    okvpn_mq_insight.message_info.default:
        class: Okvpn\Bundle\MQInsightBundle\Matcher\OriginMessageInfo

    okvpn_mq_insight.message_info.cron:
        class: Okvpn\Bundle\MQInsightBundle\Matcher\CronMessageInfo
        decorates: okvpn_mq_insight.message_info.default
        decoration_priority: 10
        arguments: ['@okvpn_mq_insight.message_info.cron.inner']

    okvpn_mq_insight.message_info.workflow_trigger:
        class: Okvpn\Bundle\MQInsightBundle\Matcher\ProcessTriggerMessageInfo
        decorates: okvpn_mq_insight.message_info.default
        decoration_priority: 5
        arguments: ['@okvpn_mq_insight.message_info.workflow_trigger.inner']
