acls:
    message_queue_view_stat:
        label: okvpn.mqinsight.view_message_queue.label
        description: okvpn.mqinsight.view_message_queue.description
        type: action
        group_name: ""
        category: "application"
