datagrids:
    message-queue-error-grid:
        acl_resource: message_queue_view_stat
        source:
            type: orm
            query:
                select:
                    - e.id as id
                    - e.created as created
                    - e.processor as processor
                    - e.message as message
                    - e.log as log
                from:
                    - { table: 'Okvpn\Bundle\MQInsightBundle\Entity\MQErrorStat', alias: e }
        columns:
            id:
                label: ID
                frontend_type: integer
            created:
                label: Created
                frontend_type: datetime
            processor:
                label: Processor
                frontend_type: string
            message:
                label: Message ID
                frontend_type: string
            log:
                type:          twig
                template:      OkvpnMQInsightBundle:Column:log.html.twig
                frontend_type: html
        properties:
            id: ~

        sorters:
            columns:
                created:
                    data_name: created
                id:
                    data_name: id
            default:
                id: DESC
        filters:
            columns:
                created:
                    type: datetime
                    data_name: created
                processor:
                    type: string
                    data_name: processor

    message-queue-processor-grid:
        acl_resource: message_queue_view_stat
        source:
            type: orm
            query:
                select:
                    - p.name as processor
                    - SUM(p.ack) as ack
                    - SUM(p.reject) as reject
                    - SUM(p.requeue) as requeue
                    - AVG(p.maxTime) as maxTime
                    - AVG(p.minTime) as minTime
                    - AVG(p.avgTime) as avgTime
                from:
                    - { table: 'Okvpn\Bundle\MQInsightBundle\Entity\ProcessorStat', alias: p }
                where:
                    and:
                        - p.created > :created
                groupBy: p.name
            bind_parameters:
                created: created
        columns:
            processor:
                label: Processor
                frontend_type: string
            ack:
                label: Ack
                frontend_type: integer
            reject:
                label: Reject
                frontend_type: integer
            requeue:
                label: Requeue
                frontend_type: integer
            avgTime:
                label: Avg
                type:          twig
                template:      OkvpnMQInsightBundle:Column:avg.html.twig
                frontend_type: html
            maxTime:
                label: Max
                type:          twig
                template:      OkvpnMQInsightBundle:Column:max.html.twig
                frontend_type: html
            minTime:
                label: Min
                type:          twig
                template:      OkvpnMQInsightBundle:Column:min.html.twig
                frontend_type: html
        options:
            toolbarOptions:
                pageSize:
                    items: [10]
                    default_per_page: 10
