datagrids:
    message-queue-error-grid:
        acl_resource: message_queue_view_stat
        source:
            type: orm
            query:
                select:
                    - e.id as id
                    - e.created as created
                    - e.processor as processor
                    - e.message as message
                    - e.log as log
                from:
                    - { table: 'Okvpn\Bundle\MQInsightBundle\Entity\MQErrorStat', alias: e }
        columns:
            id:
                label: ID
                frontend_type: integer
            created:
                label: oro.ui.created_at
                frontend_type: datetime
            processor:
                label: okvpn.mqinsight.processor.label
                frontend_type: string
            message:
                label: Message ID
                frontend_type: string
            log:
                type:          twig
                template:      OkvpnMQInsightBundle:Column:log.html.twig
                frontend_type: html
        properties:
            id: ~

        sorters:
            columns:
                created:
                    data_name: created
                id:
                    data_name: id
                processor:
                    data_name: processor
            default:
                id: DESC
        filters:
            columns:
                created:
                    type: datetime
                    data_name: created
                processor:
                    type: string
                    data_name: processor

    message-queue-processor-grid:
        acl_resource: message_queue_view_stat
        source:
            type: orm
            query:
                select:
                    - p.name as processor
                    - SUM(p.ack) as ack
                    - SUM(p.reject) as reject
                    - SUM(p.requeue) as requeue
                    - MAX(p.maxTime) as maxTime
                    - MIN(p.minTime) as minTime
                    - >
                      SUM(p.avgTime*(p.ack + p.reject + p.requeue))/(
                        CASE WHEN SUM(p.ack + p.reject + p.requeue) > 0 THEN SUM(p.ack + p.reject + p.requeue) ELSE 1 END
                      ) as avgTime
                from:
                    - { table: 'Okvpn\Bundle\MQInsightBundle\Entity\ProcessorStat', alias: p }
                where:
                    and:
                        - p.created > :created
                        - p.name NOT IN ('idle', 'system')
                groupBy: p.name
            bind_parameters:
                created: created
        columns:
            processor:
                label: okvpn.mqinsight.processor.label
                frontend_type: string
            ack:
                label: okvpn.mqinsight.ack.label
                frontend_type: integer
            reject:
                label: okvpn.mqinsight.reject.label
                frontend_type: integer
            requeue:
                label: okvpn.mqinsight.requeue.label
                frontend_type: integer
            avgTime:
                label: okvpn.mqinsight.avg_time.label
                type:          twig
                template:      OkvpnMQInsightBundle:Column:avg.html.twig
                frontend_type: html
            maxTime:
                label: okvpn.mqinsight.max_time.label
                type:          twig
                template:      OkvpnMQInsightBundle:Column:max.html.twig
                frontend_type: html
            minTime:
                label: okvpn.mqinsight.min_time.label
                type:          twig
                template:      OkvpnMQInsightBundle:Column:min.html.twig
                frontend_type: html
        options:
            toolbarOptions:
                pageSize:
                    items: [15]
                    default_per_page: 15
