navigation:
    menu_config:
        items:
            okvpn_message_queue:
                label:    okvpn.mqinsight.menu_config.label
                route:    'okvpn_mq_insight_status'
                position: 62
                extras:
                    description: 'Queue status'
                    routes:      ['okvpn_mq_insight_*']

        tree:
            application_menu:
                children:
                    system_tab:
                        children:
                            okvpn_message_queue: ~

    titles:
        okvpn_mq_insight_status: okvpn.mqinsight.menu_config.title
